name: Deploy to GitHub pages
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache cargo binaries
        id: cache-bin
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin
      - name: Install dependencies
        if: steps.cache-bin.outputs.cache-hit != 'true'
        run: |
          (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
          (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
          cargo install-update -a
      - name: Cleanup GitHub Pages
        run: |
          git switch gh-pages
          ls -A | grep -v "^\.git$" | xargs rm -r # remove everything
          git restore --source=origin/master . # restore as if we were on master
      - name: Build
        run: mdbook build
      - name: Deploy
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add * || true # add all the changes
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -am "Deploy to GitHub Pages."
          git push origin gh-pages # add the new deployment
